export const epList = [
	{command: '\\dfrac{b}{a}', class: 'dfrac{b}{a}'},
	{command: 'x_{a}', class: 'x_{a}'},
	{command: 'x^b', class: 'x^b'},
	{command: 'x_{a}^b', class: 'x_{a}^b'},
	{command: '\\sqrt{x}', class: 'sqrt{x}'},
	{command: '\\sqrt[y]{x}', class: 'sqrt[y]{x}'},
	{command: '\\bar{x}', class: 'bar{x}'},
	{command: '\\tilde{x}', class: 'tilde{x}'},
	{command: '\\vec{x}', class: 'vec{x}'},
	{command: '\\hat{x}', class: 'hat{x}'},
	{command: '\\check{x}', class: 'check{x}'},
	{command: '\\dot{x}', class: 'dot{x}'},
	{command: '\\ddot{x}', class: 'ddot{x}'},
	{command: '\\left\\{ x \\right\\}', class: 'left{x right}'},
	{command: '\\vert', class: 'vert'},
	{ command: '\\vert x \\vert', class: 'vert x vert' },
]

export const funcList = [
	{command: '\\sin x', class: 'sin x'},
	{command: '\\cos x', class: 'cos x'},
	{command: '\\tan x', class: 'tan x'},
	{command: '\\cot x', class: 'cot x'},
	{command: '\\int_{a}^{b}', class: 'int_{a}^{b}'},
	{command: '\\oint_{a}^{b}', class: 'oint_{a}^{b}'},
	{command: '\\bigcap_{a}^{b}', class: 'bigcap_{a}^{b}'},
	{command: '\\bigcup_{a}^{b}', class: 'bigcup_{a}^{b}'},
	{command: '\\sum_{a}^b', class: 'sum_{a}^b'},
	{command: '\\sum\\nolimits_{a}^b', class: 'sumnolimits_{a}^b'},
	{command: '\\prod_{i=1}^n', class: 'prod_{i=1}^n'},
	{command: '\\coprod_{i=1}^n', class: 'coprod_{i=1}^n'},
	{command: '\\prod\\nolimits_{i=1}^n', class: 'prodnolimits_{i=1}^n'},
	{command: '\\coprod\\nolimits_{i=1}^n', class: 'coprodnolimits_{i=1}^n'},
	{command: '\\ln x', class: 'ln x'},
	{command: '\\log_x y', class: 'log_x y'},
	{command: '\\lg x', class: 'lg x'},
	{command: '\\lim_{x\\to0} y', class: 'lim_{xto0} y'},
	{command: '\\lim\\nolimits_{x\\to0} y', class: 'limnolimits_{xto0} y'},
]

export const esList = [
	{command: '\\alpha', class: 'alpha'},
	{command: '\\beta', class: 'beta'},
	{command: '\\gamma', class: 'gamma'},
	{command: '\\delta', class: 'delta'},
	{command: '\\varepsilon', class: 'varepsilon'},
	{command: '\\epsilon', class: 'epsilon'},
	{command: '\\zeta', class: 'zeta'},
	{command: '\\eta', class: 'eta'},
	{command: '\\theta', class: 'theta'},
	{command: '\\vartheta', class: 'vartheta'},
	{command: '\\iota', class: 'iota'},
	{command: '\\kappa', class: 'kappa'},
	{command: '\\lambda', class: 'lambda'},
	{command: '\\mu', class: 'mu'},
	{command: '\\nu', class: 'nu'},
	{command: '\\xi', class: 'xi'},
	{command: '\\omicron', class: 'omicron'},
	{command: '\\pi', class: 'pi'},
	{command: '\\varpi', class: 'varpi'},
	{command: '\\rho', class: 'rho'},
	{command: '\\varrho', class: 'varrho'},
	{command: '\\sigma', class: 'sigma'},
	{command: '\\varsigma', class: 'varsigma'},
	{command: '\\tau', class: 'tau'},
	{command: '\\upsilon', class: 'upsilon'},
	{command: '\\varphi', class: 'varphi'},
	{command: '\\phi', class: 'phi'},
	{command: '\\chi', class: 'chi'},
	{command: '\\psi', class: 'psi'},
	{command: '\\omega', class: 'omega'},
	{command: '\\Gamma', class: 'Gamma_'},
	{command: '\\Delta', class: 'Delta_'},
	{command: '\\Theta', class: 'Theta_'},
	{command: '\\Lambda', class: 'Lambda_'},
	{command: '\\Xi', class: 'Xi_'},
	{command: '\\Pi', class: 'Pi_'},
	{command: '\\Sigma', class: 'Sigma_'},
	{command: '\\Upsilon', class: 'Upsilon_'},
	{command: '\\Phi', class: 'Phi_'},
	{command: '\\Psi', class: 'Psi_'},
	{command: '\\Omega', class: 'Omega_'},
]

export const csList = [
	{command: '\\leq', class: 'leq'},
	{command: '\\geq', class: 'geq'},
	{command: '\\pm', class: 'pm'},
	{command: '\\mp', class: 'mp'},
	{command: '\\times', class: 'times'},
	{command: '\\div', class: 'div'},
	{command: '\\neq', class: 'neq'},
	{command: '\\approx', class: 'approx'},
	{command: '\\equiv', class: 'equiv'},
	{command: '\\cong', class: 'cong'},
	{command: '\\cap', class: 'cap'},
	{command: '\\cup', class: 'cup'},
	{command: '\\exists', class: 'exists'},
	{command: '\\nexist', class: 'nexists'},
	{command: '\\forall', class: 'forall'},
	{command: '\\in', class: 'in'},
	{command: '\\notin', class: 'notin'},
	{command: '\\ni', class: 'ni'},
	{command: '\\subset', class: 'subset'},
	{command: '\\supset', class: 'supset'},
	{command: '\\subseteq', class: 'subseteq'},
	{command: '\\supseteq', class: 'supseteq'},
	{command: '\\nsubseteq', class: 'nsubseteq'},
	{command: '\\nsupseteq', class: 'nsupseteq'},
	{command: '\\land', class: 'land'},
	{command: '\\lor', class: 'lor'},
	{command: '\\ast', class: 'ast'},
	{command: '\\star', class: 'star'},
	{command: '\\circ', class: 'circ'},
	{command: '\\bullet', class: 'bullet'},
	{command: '\\cdot', class: 'cdot'},
	{command: '\\oplus', class: 'oplus'},
	{command: '\\ominus', class: 'ominus'},
	{command: '\\otimes', class: 'otimes'},
	{command: '\\oslash', class: 'oslash'},
	{command: '\\odot', class: 'odot'},
	{command: '&lrtri;', class: 'lrtri'},
	{command: '\\triangle', class: 'triangle'},
	{command: '&squ;', class: 'squ'},
	{command: '&fltns;', class: 'fltns'},
	{command: '\\diamondsuit', class: 'diamondsuit'},
	{command: '\\because', class: 'because'},
	{command: '\\therefore', class: 'therefore'},
]

export const ssList = [
	{command: '\\ll', class: 'll'},
	{command: '\\gg', class: 'gg'},
	{command: '\\sqsubset', class: 'sqsubset'},
	{command: '\\sqsupset', class: 'sqsupset'},
	{command: '\\sqsubseteq', class: 'sqsubseteq'},
	{command: '\\sqsupseteq', class: 'sqsupseteq'},
	{command: '\\preceq', class: 'preceq'},
	{command: '\\succeq', class: 'succeq'},
	{command: '\\doteq', class: 'doteq'},
	{command: '\\propto', class: 'propto'},
	{command: '\\infty', class: 'infty'},
	{command: '\\asymp', class: 'asymp'},
	{command: '\\vdash', class: 'vdash'},
	{command: '\\dashv', class: 'dashv'},
	{command: '\\prec', class: 'prec'},
	{command: '\\succ', class: 'succ'},
	{command: '\\sphericalangle', class: 'sphericalangle'},
	{command: '\\measuredangle', class: 'measuredangle'},
	{command: '\\angle', class: 'angle'},
	{command: '\\rightarrow', class: 'rightarrow'},
	{command: '\\leftarrow', class: 'leftarrow'},
	{command: '\\implies', class: 'implies'},
	{command: '\\Rightarrow', class: 'Rightarrow_'},
	{command: '\\iff', class: 'iff'},
	{command: '\\Leftrightarrow', class: 'Leftrightarrow_'},
	{command: '\\leftrightarrow', class: 'leftrightarrow'},
	{command: '\\uparrow', class: 'uparrow'},
	{command: '\\downarrow', class: 'downarrow'},
	{command: '\\Uparrow', class: 'Uparrow_'},
	{command: '\\Downarrow', class: 'Downarrow_'},
	{command: '\\top', class: 'top'},
	{command: '\\bot', class: 'bot'},
	{command: '\/\/', class: 'parallet'},
	{command: '\\lceil', class: 'lceil'},
	{command: '\\rceil', class: 'rceil'},
	{command: '\\lfloor', class: 'lfloor'},
	{command: '\\rfloor', class: 'rfloor'},
	{command: '\\;', class: ';'},
]