module.exports = {

	'math': require('../../static/SVG/math.svg'),

	'dfrac{b}{a}': require('../../static/SVG/dfrac{b}{a}.svg'),
	'x_{a}': require('../../static/SVG/x_{a}.svg'),
	'x^b': require('../../static/SVG/x^b.svg'),
	'x_{a}^b': require('../../static/SVG/x_{a}^b.svg'),
	'sqrt{x}': require('../../static/SVG/sqrt{x}.svg'),
	'sqrt[y]{x}': require('../../static/SVG/sqrt[y]{x}.svg'),
	'bar{x}': require('../../static/SVG/bar{x}.svg'),
	'tilde{x}': require('../../static/SVG/tilde{x}.svg'),
	'vec{x}': require('../../static/SVG/vec{x}.svg'),
	'hat{x}': require('../../static/SVG/hat{x}.svg'),
	'check{x}': require('../../static/SVG/check{x}.svg'),
	'dot{x}': require('../../static/SVG/dot{x}.svg'),
	'ddot{x}': require('../../static/SVG/ddot{x}.svg'),
	'left{x right}': require('../../static/SVG/left{ x right}.svg'),
	'vert': require('../../static/SVG/vert.svg'),
	'vert x vert': require('../../static/SVG/vert x vert.svg'),

	'sin x': require('../../static/SVG/sin x.svg'),
	'cos x': require('../../static/SVG/cos x.svg'),
	'tan x': require('../../static/SVG/tan x.svg'),
	'cot x': require('../../static/SVG/cot x.svg'),
	'int_{a}^{b}': require('../../static/SVG/int_{a}^{b}.svg'),
	'oint_{a}^{b}': require('../../static/SVG/oint_{a}^{b}.svg'),
	'bigcap_{a}^{b}': require('../../static/SVG/bigcap_{a}^{b}.svg'),
	'bigcup_{a}^{b}': require('../../static/SVG/bigcup_{a}^{b}.svg'),
	'sum_{a}^b': require('../../static/SVG/sum_{a}^b.svg'),
	'sumnolimits_{a}^b': require('../../static/SVG/sumnolimits_{a}^b.svg'),
	'prod_{i=1}^n': require('../../static/SVG/prod_{i=1}^n.svg'),
	'coprod_{i=1}^n': require('../../static/SVG/coprod_{i=1}^n.svg'),
	'prodnolimits_{i=1}^n': require('../../static/SVG/prodnolimits_{i=1}^n.svg'),
	'coprodnolimits_{i=1}^n': require('../../static/SVG/coprodnolimits_{i=1}^n.svg'),
	'ln x': require('../../static/SVG/ln x.svg'),
	'log_x y': require('../../static/SVG/log_x y.svg'),
	'lg x': require('../../static/SVG/lg x.svg'),
	'lim_{xto0} y': require('../../static/SVG/lim_{xto0} y.svg'),
	'limnolimits_{xto0} y': require('../../static/SVG/limnolimits_{xto0} y.svg'),

	'alpha': require('../../static/SVG/alpha.svg'),
	'beta': require('../../static/SVG/beta.svg'),
	'gamma': require('../../static/SVG/gamma.svg'),
	'delta': require('../../static/SVG/delta.svg'),
	'varepsilon': require('../../static/SVG/varepsilon.svg'),
	'epsilon': require('../../static/SVG/epsilon.svg'),
	'zeta': require('../../static/SVG/zeta.svg'),
	'eta': require('../../static/SVG/eta.svg'),
	'theta': require('../../static/SVG/theta.svg'),
	'vartheta': require('../../static/SVG/vartheta.svg'),
	'iota': require('../../static/SVG/iota.svg'),
	'kappa': require('../../static/SVG/kappa.svg'),
	'lambda': require('../../static/SVG/lambda.svg'),
	'mu': require('../../static/SVG/mu.svg'),
	'nu': require('../../static/SVG/nu.svg'),
	'xi': require('../../static/SVG/xi.svg'),
	'omicron': require('../../static/SVG/omicron.svg'),
	'pi': require('../../static/SVG/pi.svg'),
	'varpi': require('../../static/SVG/varpi.svg'),
	'rho': require('../../static/SVG/rho.svg'),
	'varrho': require('../../static/SVG/varrho.svg'),
	'sigma': require('../../static/SVG/sigma.svg'),
	'varsigma': require('../../static/SVG/varsigma.svg'),
	'tau': require('../../static/SVG/tau.svg'),
	'upsilon': require('../../static/SVG/upsilon.svg'),
	'varphi': require('../../static/SVG/varphi.svg'),
	'phi': require('../../static/SVG/phi.svg'),
	'chi': require('../../static/SVG/chi.svg'),
	'psi': require('../../static/SVG/psi.svg'),
	'omega': require('../../static/SVG/omega.svg'),
	'Gamma_': require('../../static/SVG/Gamma_.svg'),
	'Delta_': require('../../static/SVG/Delta_.svg'),
	'Theta_': require('../../static/SVG/Theta_.svg'),
	'Lambda_': require('../../static/SVG/Lambda_.svg'),
	'Xi_': require('../../static/SVG/Xi_.svg'),
	'Pi_': require('../../static/SVG/Pi_.svg'),
	'Sigma_': require('../../static/SVG/Sigma_.svg'),
	'Upsilon_': require('../../static/SVG/Upsilon_.svg'),
	'Phi_': require('../../static/SVG/Phi_.svg'),
	'Psi_': require('../../static/SVG/Psi_.svg'),
	'Omega_': require('../../static/SVG/Omega_.svg'),

	'leq': require('../../static/SVG/leq.svg'),
	'geq': require('../../static/SVG/geq.svg'),
	'pm': require('../../static/SVG/pm.svg'),
	'mp': require('../../static/SVG/mp.svg'),
	'times': require('../../static/SVG/times.svg'),
	'div': require('../../static/SVG/div.svg'),
	'neq': require('../../static/SVG/neq.svg'),
	'approx': require('../../static/SVG/approx.svg'),
	'equiv': require('../../static/SVG/equiv.svg'),
	'cong': require('../../static/SVG/cong.svg'),
	'cap': require('../../static/SVG/cap.svg'),
	'cup': require('../../static/SVG/cup.svg'),
	'exists': require('../../static/SVG/exists.svg'),
	'nexists': require('../../static/SVG/nexists.svg'),
	'forall': require('../../static/SVG/forall.svg'),
	'in': require('../../static/SVG/in.svg'),
	'notin': require('../../static/SVG/notin.svg'),
	'ni': require('../../static/SVG/ni.svg'),
	'subset': require('../../static/SVG/subset.svg'),
	'supset': require('../../static/SVG/supset.svg'),
	'subseteq': require('../../static/SVG/subseteq.svg'),
	'supseteq': require('../../static/SVG/supseteq.svg'),
	'nsubseteq': require('../../static/SVG/nsubseteq.svg'),
	'nsupseteq': require('../../static/SVG/nsupseteq.svg'),
	'land': require('../../static/SVG/land.svg'),
	'lor': require('../../static/SVG/lor.svg'),
	'ast': require('../../static/SVG/ast.svg'),
	'star': require('../../static/SVG/star.svg'),
	'circ': require('../../static/SVG/circ.svg'),
	'bullet': require('../../static/SVG/bullet.svg'),
	'cdot': require('../../static/SVG/cdot.svg'),
	'oplus': require('../../static/SVG/oplus.svg'),
	'ominus': require('../../static/SVG/ominus.svg'),
	'otimes': require('../../static/SVG/otimes.svg'),
	'oslash': require('../../static/SVG/oslash.svg'),
	'odot': require('../../static/SVG/odot.svg'),
	'lrtri': require('../../static/SVG/lrtri.svg'),
	'triangle': require('../../static/SVG/triangle.svg'),
	'squ': require('../../static/SVG/Box.svg'),
	'fltns': require('../../static/SVG/fltns.svg'),
	'diamondsuit': require('../../static/SVG/diamondsuit.svg'),
	'because': require('../../static/SVG/because.svg'),
	'therefore': require('../../static/SVG/therefore.svg'),

	'll': require('../../static/SVG/ll.svg'),
	'gg': require('../../static/SVG/gg.svg'),
	'sqsubset': require('../../static/SVG/sqsubset.svg'),
	'sqsupset': require('../../static/SVG/sqsupset.svg'),
	'sqsubseteq': require('../../static/SVG/sqsubseteq.svg'),
	'sqsupseteq': require('../../static/SVG/sqsupseteq.svg'),
	'preceq': require('../../static/SVG/preceq.svg'),
	'succeq': require('../../static/SVG/succeq.svg'),
	'doteq': require('../../static/SVG/doteq.svg'),
	'propto': require('../../static/SVG/propto.svg'),
	'infty': require('../../static/SVG/infty.svg'),
	'asymp': require('../../static/SVG/asymp.svg'),
	'vdash': require('../../static/SVG/vdash.svg'),
	'dashv': require('../../static/SVG/dashv.svg'),
	'prec': require('../../static/SVG/prec.svg'),
	'succ': require('../../static/SVG/succ.svg'),
	'sphericalangle': require('../../static/SVG/sphericalangle.svg'),
	'measuredangle': require('../../static/SVG/measuredangle.svg'),
	'angle': require('../../static/SVG/angle.svg'),
	'rightarrow': require('../../static/SVG/rightarrow.svg'),
	'leftarrow': require('../../static/SVG/leftarrow.svg'),
	'implies': require('../../static/SVG/implies.svg'),
	'Rightarrow_': require('../../static/SVG/Rightarrow_.svg'),
	'iff': require('../../static/SVG/iff.svg'),
	'Leftrightarrow_': require('../../static/SVG/Leftrightarrow_.svg'),
	'leftrightarrow': require('../../static/SVG/leftrightarrow.svg'),
	'uparrow': require('../../static/SVG/uparrow.svg'),
	'downarrow': require('../../static/SVG/downarrow.svg'),
	'Uparrow_': require('../../static/SVG/Uparrow_.svg'),
	'Downarrow_': require('../../static/SVG/Downarrow_.svg'),
	'top': require('../../static/SVG/top.svg'),
	'bot': require('../../static/SVG/bot.svg'),
	'parallet': require('../../static/SVG/parallel.svg'),
	'lceil': require('../../static/SVG/lceil.svg'),
	'rceil': require('../../static/SVG/rceil.svg'),
	'lfloor': require('../../static/SVG/lfloor.svg'),
	'rfloor': require('../../static/SVG/rfloor.svg'),
	';': require('../../static/SVG/;.svg'),
}